version: '3'

services:
  horizont_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PORT=80
    volumes:
    - ./client/dist:/horizont_web/client/dist
    - .:/horizont_web:delegated
    - /horizont_web/server/node_modules
    restart: unless-stopped